### ISSUE TITLE
Property access of array object at index

### ISSUE THREAD

**Issue by jwhitmarsh** [davesnx/query-json#19]
I am very likely doing something wrong, but in `jq` you can write `.exampleArray[2].desiredProperty` to get the value of `desiredProperty`, however that doesn't seem to be supported by `query-json`. Have I got that syntax correct?

**Comment by davesnx** [comment]
Hey @jwhitmarsh 

There's a bug on the parser right now, where `.exampleArray[2].desiredProperty` doesn't like the fact that a dot is after the `[]`. I will fix in the next version.

As a workaround you can always do `.exampleArray[2] | .desiredProperty`

**Comment by davesnx** [comment]
It's fixed on v0.5.8

Thanks for reporting
